# Generated by Django 4.1.2 on 2022-11-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectReport',
            new_name='OrderReport',
        ),
        migrations.AlterModelOptions(
            name='orderreport',
            options={'verbose_name_plural': 'Order'},
        ),
    ]
