# Generated by Django 4.1.2 on 2022-12-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'الملف الشخصى', 'verbose_name_plural': 'Profiles'},
        ),
    ]
