# Generated by Django 4.1.2 on 2022-10-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('engineer', models.CharField(blank=True, max_length=250, null=True)),
                ('photo_project', models.ImageField(blank=True, null=True, upload_to='photos_file')),
                ('photo_engineer', models.ImageField(blank=True, null=True, upload_to='photos_file')),
                ('proid', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retal_cost_day', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retal_priod', models.IntegerField(blank=True, null=True)),
                ('total_retal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('in progress projects', 'in progress projects'), ('joint projects', 'joint projects'), ('completed projects', 'completed projects')], max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
