# Generated by Django 4.1.2 on 2022-10-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_emailsender_emailsubscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
