# Generated by Django 4.1.2 on 2022-11-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_emailsubscribe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='datails',
            field=models.TextField(null=True),
        ),
    ]
