# Generated by Django 4.1.2 on 2022-11-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_project_datails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='retal_cost_day',
        ),
        migrations.RemoveField(
            model_name='project',
            name='retal_priod',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_retal',
        ),
    ]
