# Generated by Django 4.1.2 on 2022-11-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_project_retal_cost_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='engineer',
            new_name='place',
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name_engineer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_project_two',
            field=models.ImageField(blank=True, null=True, upload_to='photos_file'),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo_clients', models.ImageField(blank=True, null=True, upload_to='photos_file')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.project')),
            ],
        ),
    ]
