# Generated by Django 4.1.2 on 2022-11-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_engineer_project_place_project_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='place',
            new_name='engineer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_engineer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='photo_project_two',
        ),
    ]
