# Generated by Django 4.1.2 on 2022-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_place_project_engineer_remove_project_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='place',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
