# Generated by Django 4.1.2 on 2022-11-22 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_project_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='sales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.clients'),
        ),
    ]
