# Generated by Django 4.1.2 on 2022-11-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_clients_project_project_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
