# Generated by Django 4.1.2 on 2022-11-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_clients_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='amount',
        ),
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
