# Generated by Django 4.1.2 on 2022-11-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_clients_amount_project_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
