# Generated by Django 4.1.2 on 2022-11-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_clients_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='clients',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
