# Generated by Django 4.1.2 on 2022-11-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_project_status_clients_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecievMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('message', models.TextField(null=True)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
    ]
