# Generated by Django 4.1.2 on 2022-11-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_recievmessages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecievMessages',
        ),
    ]
