# Generated by Django 4.1.2 on 2022-11-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_sales_alter_project_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='cost',
        ),
        migrations.AddField(
            model_name='sales',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
