# Generated by Django 4.1.2 on 2022-11-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_transaction_remove_project_sales_category_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.sales'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
