# Generated by Django 4.1.2 on 2022-11-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction',
            new_name='sales',
        ),
    ]
