# Generated by Django 4.1.2 on 2022-11-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_rename_transaction_order_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.order'),
        ),
    ]
