# Generated by Django 4.1.2 on 2022-11-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_project_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='order',
            new_name='sales',
        ),
    ]
