# Generated by Django 4.1.2 on 2022-11-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_rename_order_project_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sales',
        ),
    ]
