# Generated by Django 4.1.2 on 2022-11-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_remove_project_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='items',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Stripe'), (2, 'Paypal')], null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
