# Generated by Django 4.1.2 on 2022-11-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_sales_created_at_sales_customer_sales_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='items',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sales',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
