# Generated by Django 4.1.2 on 2022-12-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'cash'), (2, 'credit')], null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'constructing')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
