# Generated by Django 4.1.2 on 2022-12-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_remove_order_amount_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Clients', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='emailsender',
            options={'verbose_name': 'EmailSender', 'verbose_name_plural': 'EmailSenders'},
        ),
        migrations.AlterModelOptions(
            name='emailsubscribe',
            options={'verbose_name': 'EmailSubscribe', 'verbose_name_plural': 'EmailSubscribes'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='recievmessages',
            options={'verbose_name': 'RecievMessages', 'verbose_name_plural': 'RecievMessages'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sales', 'verbose_name_plural': 'Sales'},
        ),
    ]
