# Generated by Django 4.1.2 on 2022-12-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_alter_category_options_alter_clients_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'العملاء', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='emailsender',
            options={'verbose_name': 'البريد المرسل', 'verbose_name_plural': 'ارسال بريد'},
        ),
        migrations.AlterModelOptions(
            name='emailsubscribe',
            options={'verbose_name': 'البريد المشترك', 'verbose_name_plural': 'البريد المشترك'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'الطلب', 'verbose_name_plural': ' الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'صوره المشروع', 'verbose_name_plural': 'المشروعات'},
        ),
        migrations.AlterModelOptions(
            name='recievmessages',
            options={'verbose_name': 'مستلم رساله', 'verbose_name_plural': 'مستلم رساله'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'المبيعات', 'verbose_name_plural': 'المبيعات'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'مدفوع'), (2, 'اجل')], null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.IntegerField(choices=[(0, 'تحت الانشاء'), (1, 'منتهيه'), (2, 'تحت الانشاء')], default=0, null=True),
        ),
    ]
